export interface Project {
  id: number;
  title: string;
  aplication: string;
  image: string;
  images?: string[];
  tag: string;
}

export const categories = [
  "Todos",
  "OOH",
  "PDV",
  "Projetos especiais",
  "Linha ECO",
];

export const projects: Project[] = [
  {
    id: 1,
    title: "Disney",
    aplication: "Cenografia",
    image: "/images/pdv/disney/disney1.webp",
    images: [
      "/images/pdv/disney/disney1.webp",
      "/images/pdv/disney/disney2.webp",
      "/images/pdv/disney/disney3.webp",
    ],
    tag: "PDV",
  },
  {
    id: 2,
    title: "Marvel",
    aplication: "Cenografia",
    image: "/images/pdv/herois/heroi1.jpg",
    images: [
      "/images/pdv/herois/heroi1.jpg",
      "/images/pdv/herois/heroi2.jpg",
      "/images/pdv/herois/heroi3.webp",
    ],
    tag: "PDV",
  },
  {
    id: 3,
    title: "Mickey Mouse",
    aplication: "Stands",
    image: "/images/pdv/mickey/mickey1.jpg",
    images: [
      "/images/pdv/mickey/mickey1.jpg",
      "/images/pdv/mickey/mickey2.jpg",
      "/images/pdv/mickey/mickey3.jpg",
    ],
    tag: "PDV",
  },
  {
    id: 4,
    title: "Princesas",
    aplication: "Cenografia",
    image: "/images/pdv/princesas/princesas1.jpg",
    images: [
      "/images/pdv/princesas/princesas1.jpg",
      "/images/pdv/princesas/princesas2.jpg",
    ],
    tag: "PDV",
  },
  {
    id: 5,
    title: "99 Food",
    aplication: "Metrôs e trens",
    image: "/images/projetos-especiais/99food/991.webp",
    images: [
      "/images/projetos-especiais/99food/991.webp",
      "/images/projetos-especiais/99food/992.webp",
      "/images/projetos-especiais/99food/993.webp",
    ],
    tag: "Projetos especiais",
  },
  {
    id: 6,
    title: "FallOut",
    aplication: "Metrôs e trens",
    image: "/images/projetos-especiais/fallout/fallout1.webp",
    images: [
      "/images/projetos-especiais/fallout/fallout1.webp",
      "/images/projetos-especiais/fallout/fallout2.webp",
      "/images/projetos-especiais/fallout/fallout3.webp",
    ],
    tag: "Projetos especiais",
  },
  {
    id: 7,
    title: "Lacta",
    aplication: "Eventos e ativações",
    image: "/images/projetos-especiais/lacta/lacta1.webp",
    images: [
      "/images/projetos-especiais/lacta/lacta1.webp",
      "/images/projetos-especiais/lacta/lacta2.webp",
      "/images/projetos-especiais/lacta/lacta3.webp",
    ],
    tag: "Projetos especiais",
  },
  {
    id: 8,
    title: "Bob Esponja",
    aplication: "Metrôs e trens",
    image: "/images/projetos-especiais/bobesponja/bob3.webp",
    images: [
      "/images/projetos-especiais/bobesponja/bob1.webp",
      "/images/projetos-especiais/bobesponja/bob2.webp",
      "/images/projetos-especiais/bobesponja/bob3.webp",
    ],
    tag: "Projetos especiais",
  },
  {
    id: 9,
    title: "Nubank",
    aplication: "Metrôs e trens",
    image: "/images/projetos-especiais/nubank/nubank3.webp",
    images: [
      "/images/projetos-especiais/nubank/nubank1.webp",
      "/images/projetos-especiais/nubank/nubank2.webp",
      "/images/projetos-especiais/nubank/nubank3.webp",
    ],
    tag: "Projetos especiais",
  },
  {
    id: 10,
    title: "Pepsi",
    aplication: "Metrôs e trens",
    image: "/images/projetos-especiais/pepsi/pepsi1.webp",
    images: [
      "/images/projetos-especiais/pepsi/pepsi1.webp",
      "/images/projetos-especiais/pepsi/pepsi2.webp",
      "/images/projetos-especiais/pepsi/pepsi3.webp",
    ],
    tag: "Projetos especiais",
  },
  {
    id: 11,
    title: "Rexona",
    aplication: "Metrôs e trens",
    image: "/images/projetos-especiais/rexona/rexona3.jpg",
    images: [
      "/images/projetos-especiais/rexona/rexona1.jpg",
      "/images/projetos-especiais/rexona/rexona2.jpg",
      "/images/projetos-especiais/rexona/rexona3.jpg",
      "/images/projetos-especiais/rexona/rexona4.jpg",
      "/images/projetos-especiais/rexona/rexona5.jpg",
    ],
    tag: "Projetos especiais",
  },
  {
    id: 12,
    title: "The Smurfs",
    aplication: "Eventos e ativações",
    image: "/images/projetos-especiais/smurfs/smurfs1.png",
    images: [
      "/images/projetos-especiais/smurfs/smurfs1.png",
      "/images/projetos-especiais/smurfs/smurfs2.png",
      "/images/projetos-especiais/smurfs/smurfs3.png",
    ],
    tag: "Projetos especiais",
  },
  {
    id: 13,
    title: "As Tartarugas Ninjas",
    aplication: "Eventos e ativações",
    image: "/images/projetos-especiais/tartarugas-ninja/tartaruga1.jpg",
    images: [
      "/images/projetos-especiais/tartarugas-ninja/tartaruga1.jpg",
      "/images/projetos-especiais/tartarugas-ninja/tartaruga2.jpg",
      "/images/projetos-especiais/tartarugas-ninja/tartaruga3.jpg",
      "/images/projetos-especiais/tartarugas-ninja/tartaruga4.jpg",
    ],
    tag: "Projetos especiais",
  },
  {
    id: 14,
    title: "Keeta",
    aplication: "Vias urbanas",
    image: "/images/projetos-especiais/keeta/keeta1.webp",
    images: [
      "/images/projetos-especiais/keeta/keeta1.webp",
      "/images/projetos-especiais/keeta/keeta2.webp",
      "/images/projetos-especiais/keeta/keeta3.webp",
    ],
    tag: "Projetos especiais",
  },
  {
    id: 15,
    title: "Round 6",
    aplication: "Metrôs e trens",
    image: "/images/projetos-especiais/round6/r62.png",
    images: [
      "/images/projetos-especiais/round6/r61.png",
      "/images/projetos-especiais/round6/r62.png",
      "/images/projetos-especiais/round6/r63.png",
    ],
    tag: "Projetos especiais",
  },
  {
    id: 16,
    title: "Seara Bridgerton",
    aplication: "Metrôs e trens",
    image: "/images/projetos-especiais/seara/seara1.jpeg",
    images: [
      "/images/projetos-especiais/seara/seara1.jpeg",
      "/images/projetos-especiais/seara/seara2.jpeg",
      "/images/projetos-especiais/seara/seara3.jpeg",
    ],
    tag: "Projetos especiais",
  },
  {
    id: 17,
    title: "Airton Senna",
    aplication: "Metrôs e trens",
    image: "/images/projetos-especiais/senna/senna3.webp",
    images: [
      "/images/projetos-especiais/senna/senna1.webp",
      "/images/projetos-especiais/senna/senna2.webp",
      "/images/projetos-especiais/senna/senna3.webp",
    ],
    tag: "Projetos especiais",
  },
  {
    id: 18,
    title: "Stranger Things",
    aplication: "Stands",
    image: "/images/projetos-especiais/stranger-things/stranger1.webp",
    images: [
      "/images/projetos-especiais/stranger-things/stranger1.webp",
      "/images/projetos-especiais/stranger-things/stranger2.webp",
      "/images/projetos-especiais/stranger-things/stranger3.webp",
    ],
    tag: "Projetos especiais",
  },
  {
    id: 19,
    title: "Eisenbahn",
    aplication: "Metrôs e trens",
    image: "/images/projetos-especiais/eisenbahn/eisenbahn3.png",
    images: [
      "/images/projetos-especiais/eisenbahn/eisenbahn1.png",
      "/images/projetos-especiais/eisenbahn/eisenbahn2.png",
      "/images/projetos-especiais/eisenbahn/eisenbahn3.png",
    ],
    tag: "Projetos especiais",
  },
  {
    id: 20,
    title: "Amstel",
    aplication: "Metrôs e trens",
    image: "/images/ooh/amstel/amstel1.webp",
    images: [
      "/images/ooh/amstel/amstel1.webp",
      "/images/ooh/amstel/amstel2.webp",
      "/images/ooh/amstel/amstel3.webp",
    ],
    tag: "OOH",
  },
  {
    id: 21,
    title: "Intelbras",
    aplication: "Vias urbanas",
    image: "/images/ooh/intelbras/intelbras1.webp",
    images: [
      "/images/ooh/intelbras/intelbras1.webp",
      "/images/ooh/intelbras/intelbras2.webp",
      "/images/ooh/intelbras/intelbras3.webp",
    ],
    tag: "OOH",
  },
  {
    id: 22,
    title: "Bauducco",
    aplication: "Metrôs e trens",
    image: "/images/ooh/bauducco/bauducco1.webp",
    images: [
      "/images/ooh/bauducco/bauducco1.webp",
      "/images/ooh/bauducco/bauducco2.webp",
      "/images/ooh/bauducco/bauducco3.webp",
    ],
    tag: "OOH",
  },
  {
    id: 23,
    title: "Sorriso",
    aplication: "Metrôs e trens",
    image: "/images/ooh/sorriso/sorriso2.webp",
    images: [
      "/images/ooh/sorriso/sorriso1.webp",
      "/images/ooh/sorriso/sorriso2.webp",
      "/images/ooh/sorriso/sorriso3.webp",
    ],
    tag: "OOH",
  },
  {
    id: 24,
    title: "Stranger Things",
    aplication: "Vias urbanas",
    image: "/images/ooh/stranger-things/stranger9.webp",
    images: [
      "/images/ooh/stranger-things/stranger1.webp",
      "/images/ooh/stranger-things/stranger2.webp",
      "/images/ooh/stranger-things/stranger3.webp",
      "/images/ooh/stranger-things/stranger4.webp",
      "/images/ooh/stranger-things/stranger5.webp",
      "/images/ooh/stranger-things/stranger6.webp",
      "/images/ooh/stranger-things/stranger7.webp",
      "/images/ooh/stranger-things/stranger8.webp",
      "/images/ooh/stranger-things/stranger9.webp",
    ],
    tag: "OOH",
  },
  {
    id: 25,
    title: "Betano",
    aplication: "Vias urbanas",
    image: "/images/ooh/betano/betano1.webp",
    images: [
      "/images/ooh/betano/betano1.webp",
      "/images/ooh/betano/betano2.webp",
      "/images/ooh/betano/betano3.webp",
    ],
    tag: "OOH",
  },
  {
    id: 26,
    title: "Cielo",
    aplication: "Vias urbanas",
    image: "/images/ooh/cielo/cielo1.webp",
    images: [
      "/images/ooh/cielo/cielo1.webp",
      "/images/ooh/cielo/cielo2.webp",
      "/images/ooh/cielo/cielo3.webp",
    ],
    tag: "OOH",
  },
  {
    id: 27,
    title: "Divertidamente",
    aplication: "Metrôs e trens",
    image: "/images/ooh/divertidamente/divertidamente1.webp",
    images: [
      "/images/ooh/divertidamente/divertidamente1.webp",
      "/images/ooh/divertidamente/divertidamente2.webp",
      "/images/ooh/divertidamente/divertidamente3.webp",
    ],
    tag: "OOH",
  },
  {
    id: 28,
    title: "Hersheys",
    aplication: "Vias urbanas",
    image: "/images/ooh/hersheys/hersheys1.webp",
    images: [
      "/images/ooh/hersheys/hersheys1.webp",
      "/images/ooh/hersheys/hersheys2.webp",
      "/images/ooh/hersheys/hersheys3.webp",
    ],
    tag: "OOH",
  },
  {
    id: 29,
    title: "Avon",
    aplication: "Mobiliario urbano",
    image: "/images/ooh/avon/avon1.webp",
    images: [
      "/images/ooh/avon/avon1.webp",
      "/images/ooh/avon/avon2.webp",
      "/images/ooh/avon/avon3.webp",
    ],
    tag: "OOH",
  },
  {
    id: 30,
    title: "Garnier",
    aplication: "Metrôs e trens",
    image: "/images/ooh/garnier/garnier1.webp",
    images: [
      "/images/ooh/garnier/garnier1.webp",
      "/images/ooh/garnier/garnier2.webp",
      "/images/ooh/garnier/garnier3.webp",
    ],
    tag: "OOH",
  },
  {
    id: 31,
    title: "Chevrolet",
    aplication: "Metrôs e trens",
    image: "/images/ooh/chevrolet/chevrolet1.webp",
    images: [
      "/images/ooh/chevrolet/chevrolet1.webp",
      "/images/ooh/chevrolet/chevrolet2.webp",
      "/images/ooh/chevrolet/chevrolet3.webp",
    ],
    tag: "OOH",
  },
  {
    id: 32,
    title: "Colgate",
    aplication: "Vias urbanas",
    image: "/images/ooh/colgate/colgate1.jpeg",
    images: [
      "/images/ooh/colgate/colgate1.jpeg",
      "/images/ooh/colgate/colgate2.jpeg",
      "/images/ooh/colgate/colgate3.jpeg",
    ],
    tag: "OOH",
  },
  {
    id: 33,
    title: "Natura",
    aplication: "Painéis",
    image: "/images/ooh/natura/natura1.png",
    images: [
      "/images/ooh/natura/natura1.png",
      "/images/ooh/natura/natura2.png",
      "/images/ooh/natura/natura3.png",
    ],
    tag: "OOH",
  },
  {
    id: 34,
    title: "Shopee",
    aplication: "Painéis",
    image: "/images/ooh/shopee/shopee1.jpg",
    images: [
      "/images/ooh/shopee/shopee1.jpg",
      "/images/ooh/shopee/shopee2.jpg",
      "/images/ooh/shopee/shopee3.jpg",
    ],
    tag: "OOH",
  },
];
